---
storage:
  path: /Users/viktor/Projects/imaginarium/storage

exporter:
  enabled: true
  port: 9360

server:
  port: 80
  uploader:
    maxSize: 50
    allow:
      - image/png
      - image/jpg
      - image/jpeg
