---
storage:
  path: /mnt/storage

exporter:
  enabled: true
  port: 9360

server:
  port: 81
  uploader:
    maxSize: 5M
    contexts:
      - context: thumbnal
        width: 320
        height: 0
      - context: article
        width: 640
        height: 0
    allow:
      - image/png
      - image/jpg
      - image/jpeg
